apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keys.b2.issei.space
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  labels:
  {{- include "backblaze-operator.labels" . | nindent 4 }}
spec:
  group: b2.issei.space
  names:
    kind: Key
    listKind: KeyList
    plural: keys
    singular: key
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.atProvider.bucketName
      name: Bucket
      type: string
    - jsonPath: .status.reconciled
      name: Reconciled
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: Key is the Schema for the keys API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: KeySpec defines the desired state of Key
            properties:
              atProvider:
                description: Define configuration at provider (https://www.backblaze.com/apidocs/b2-create-key)
                properties:
                  bucketId:
                    description: 'Optional: Instead of bucket name, you can define directly
                      a bucket ID. Leave empty to allow access to all buckets on account.'
                    type: string
                  bucketName:
                    description: Name of bucket to which key should have access. Leave
                      empty to allow access to all buckets on account.
                    type: string
                  capabilities:
                    description: 'List of capabilities that key should have. Available
                      options: "listKeys", "writeKeys", "deleteKeys", "listAllBucketNames",
                      "listBuckets", "readBuckets", "writeBuckets", "deleteBuckets",
                      "readBucketRetentions", "writeBucketRetentions", "readBucketEncryption",
                      "writeBucketEncryption", "listFiles", "readFiles", "shareFiles",
                      "writeFiles", "deleteFiles", "readFileLegalHolds", "writeFileLegalHolds",
                      "readFileRetentions", "writeFileRetentions", "bypassGovernance"'
                    items:
                      type: string
                    type: array
                  namePrefix:
                    description: 'When present, restricts access to files whose names
                      start with the prefix. Note: you need to setup bucketName or bucketId
                      when setting this.'
                    type: string
                  validDurationInSeconds:
                    description: When provided, the key will expire after the given
                      number of seconds, and will have expirationTimestamp set. Value
                      must be a positive integer, and must be less than 1000 days (in
                      seconds).
                    maximum: 86400000
                    type: integer
                type: object
              writeConnectionSecretToRef:
                description: Set where operator should save connection credentials.
                properties:
                  name:
                    description: Set name of secret where credentials should be set
                    type: string
                type: object
            type: object
          status:
            description: KeyStatus defines the observed state of Key
            properties:
              ToRecreate:
                default: false
                description: 'Internal status for operator: it will be set to true if
                  the key will need to be recreated'
                type: boolean
              atProvider:
                description: Current configuration at provider
                properties:
                  bucketId:
                    description: 'Optional: Instead of bucket name, you can define directly
                      a bucket ID. Leave empty to allow access to all buckets on account.'
                    type: string
                  bucketName:
                    description: Name of bucket to which key should have access. Leave
                      empty to allow access to all buckets on account.
                    type: string
                  capabilities:
                    description: 'List of capabilities that key should have. Available
                      options: "listKeys", "writeKeys", "deleteKeys", "listAllBucketNames",
                      "listBuckets", "readBuckets", "writeBuckets", "deleteBuckets",
                      "readBucketRetentions", "writeBucketRetentions", "readBucketEncryption",
                      "writeBucketEncryption", "listFiles", "readFiles", "shareFiles",
                      "writeFiles", "deleteFiles", "readFileLegalHolds", "writeFileLegalHolds",
                      "readFileRetentions", "writeFileRetentions", "bypassGovernance"'
                    items:
                      type: string
                    type: array
                  namePrefix:
                    description: 'When present, restricts access to files whose names
                      start with the prefix. Note: you need to setup bucketName or bucketId
                      when setting this.'
                    type: string
                  validDurationInSeconds:
                    description: When provided, the key will expire after the given
                      number of seconds, and will have expirationTimestamp set. Value
                      must be a positive integer, and must be less than 1000 days (in
                      seconds).
                    maximum: 86400000
                    type: integer
                type: object
              bucketId:
                description: 'Internal status for operator: target bucket ID'
                type: string
              keyId:
                description: 'Internal status for operator: application key ID to perform
                  some operations'
                type: string
              reconciled:
                default: false
                description: Status for resource, if it was reconciled by operator
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
